// Code generated by protoc-gen-slimrpc-node. DO NOT EDIT.
// source: a2a.proto

import {
  RpcError,
  RpcCode,
  StreamMessage_Tags,
  MulticastStreamMessage_Tags,
  type ChannelLike,
  type ServerLike,
  type ContextLike,
  type RequestStreamLike,
  type ResponseSinkLike,
  type RpcMessageContext,
  type UnaryUnaryHandler,
  type UnaryStreamHandler,
  type StreamUnaryHandler,
  type StreamStreamHandler,
} from "@agntcy/slim-bindings";
import { fromBinary, toBinary } from "@bufbuild/protobuf";
import { AgentCardSchema, CancelTaskRequestSchema, DeleteTaskPushNotificationConfigRequestSchema, GetExtendedAgentCardRequestSchema, GetTaskPushNotificationConfigRequestSchema, GetTaskRequestSchema, ListTaskPushNotificationConfigsRequestSchema, ListTaskPushNotificationConfigsResponseSchema, ListTasksRequestSchema, ListTasksResponseSchema, SendMessageRequestSchema, SendMessageResponseSchema, StreamResponseSchema, SubscribeToTaskRequestSchema, TaskPushNotificationConfigSchema, TaskSchema, type AgentCard, type CancelTaskRequest, type DeleteTaskPushNotificationConfigRequest, type GetExtendedAgentCardRequest, type GetTaskPushNotificationConfigRequest, type GetTaskRequest, type ListTaskPushNotificationConfigsRequest, type ListTaskPushNotificationConfigsResponse, type ListTasksRequest, type ListTasksResponse, type SendMessageRequest, type SendMessageResponse, type StreamResponse, type SubscribeToTaskRequest, type Task, type TaskPushNotificationConfig } from "./a2a_pb.js";
import { EmptySchema, type Empty } from "@bufbuild/protobuf/wkt";

function _toArrayBuffer(bytes: Uint8Array): ArrayBuffer {
  if (bytes.byteOffset === 0 && bytes.byteLength === bytes.buffer.byteLength) {
    return bytes.buffer as ArrayBuffer;
  }
  return bytes.slice().buffer as ArrayBuffer;
}

function _toRpcError(e: unknown): RpcError {
  if (e instanceof RpcError.Rpc || e instanceof RpcError.MulticastRpc) {
    return e;
  }
  const message = e instanceof Error ? e.message : String(e);
  return new RpcError.Rpc({ code: RpcCode.Internal, message, details: undefined });
}

export class A2AServiceClient {
  constructor(private readonly _channel: ChannelLike) {}

  async SendMessage(request: SendMessageRequest, timeout?: number, metadata?: Map<string, string>): Promise<SendMessageResponse> {
    const responseBytes = await this._channel.callUnaryAsync(
      "lf.a2a.v1.A2AService",
      "SendMessage",
      _toArrayBuffer(toBinary(SendMessageRequestSchema, request)),
      timeout,
      metadata,
    );
    return fromBinary(SendMessageResponseSchema, new Uint8Array(responseBytes));
  }

  async *SendStreamingMessage(request: SendMessageRequest, timeout?: number, metadata?: Map<string, string>): AsyncGenerator<StreamResponse> {
    const reader = await this._channel.callUnaryStreamAsync(
      "lf.a2a.v1.A2AService",
      "SendStreamingMessage",
      _toArrayBuffer(toBinary(SendMessageRequestSchema, request)),
      timeout,
      metadata,
    );
    while (true) {
      const msg = await reader.nextAsync();
      if (msg.tag === StreamMessage_Tags.End) break;
      if (msg.tag === StreamMessage_Tags.Error) throw msg.inner[0];
      yield fromBinary(StreamResponseSchema, new Uint8Array(msg.inner[0]));
    }
  }

  async GetTask(request: GetTaskRequest, timeout?: number, metadata?: Map<string, string>): Promise<Task> {
    const responseBytes = await this._channel.callUnaryAsync(
      "lf.a2a.v1.A2AService",
      "GetTask",
      _toArrayBuffer(toBinary(GetTaskRequestSchema, request)),
      timeout,
      metadata,
    );
    return fromBinary(TaskSchema, new Uint8Array(responseBytes));
  }

  async ListTasks(request: ListTasksRequest, timeout?: number, metadata?: Map<string, string>): Promise<ListTasksResponse> {
    const responseBytes = await this._channel.callUnaryAsync(
      "lf.a2a.v1.A2AService",
      "ListTasks",
      _toArrayBuffer(toBinary(ListTasksRequestSchema, request)),
      timeout,
      metadata,
    );
    return fromBinary(ListTasksResponseSchema, new Uint8Array(responseBytes));
  }

  async CancelTask(request: CancelTaskRequest, timeout?: number, metadata?: Map<string, string>): Promise<Task> {
    const responseBytes = await this._channel.callUnaryAsync(
      "lf.a2a.v1.A2AService",
      "CancelTask",
      _toArrayBuffer(toBinary(CancelTaskRequestSchema, request)),
      timeout,
      metadata,
    );
    return fromBinary(TaskSchema, new Uint8Array(responseBytes));
  }

  async *SubscribeToTask(request: SubscribeToTaskRequest, timeout?: number, metadata?: Map<string, string>): AsyncGenerator<StreamResponse> {
    const reader = await this._channel.callUnaryStreamAsync(
      "lf.a2a.v1.A2AService",
      "SubscribeToTask",
      _toArrayBuffer(toBinary(SubscribeToTaskRequestSchema, request)),
      timeout,
      metadata,
    );
    while (true) {
      const msg = await reader.nextAsync();
      if (msg.tag === StreamMessage_Tags.End) break;
      if (msg.tag === StreamMessage_Tags.Error) throw msg.inner[0];
      yield fromBinary(StreamResponseSchema, new Uint8Array(msg.inner[0]));
    }
  }

  async CreateTaskPushNotificationConfig(request: TaskPushNotificationConfig, timeout?: number, metadata?: Map<string, string>): Promise<TaskPushNotificationConfig> {
    const responseBytes = await this._channel.callUnaryAsync(
      "lf.a2a.v1.A2AService",
      "CreateTaskPushNotificationConfig",
      _toArrayBuffer(toBinary(TaskPushNotificationConfigSchema, request)),
      timeout,
      metadata,
    );
    return fromBinary(TaskPushNotificationConfigSchema, new Uint8Array(responseBytes));
  }

  async GetTaskPushNotificationConfig(request: GetTaskPushNotificationConfigRequest, timeout?: number, metadata?: Map<string, string>): Promise<TaskPushNotificationConfig> {
    const responseBytes = await this._channel.callUnaryAsync(
      "lf.a2a.v1.A2AService",
      "GetTaskPushNotificationConfig",
      _toArrayBuffer(toBinary(GetTaskPushNotificationConfigRequestSchema, request)),
      timeout,
      metadata,
    );
    return fromBinary(TaskPushNotificationConfigSchema, new Uint8Array(responseBytes));
  }

  async ListTaskPushNotificationConfigs(request: ListTaskPushNotificationConfigsRequest, timeout?: number, metadata?: Map<string, string>): Promise<ListTaskPushNotificationConfigsResponse> {
    const responseBytes = await this._channel.callUnaryAsync(
      "lf.a2a.v1.A2AService",
      "ListTaskPushNotificationConfigs",
      _toArrayBuffer(toBinary(ListTaskPushNotificationConfigsRequestSchema, request)),
      timeout,
      metadata,
    );
    return fromBinary(ListTaskPushNotificationConfigsResponseSchema, new Uint8Array(responseBytes));
  }

  async GetExtendedAgentCard(request: GetExtendedAgentCardRequest, timeout?: number, metadata?: Map<string, string>): Promise<AgentCard> {
    const responseBytes = await this._channel.callUnaryAsync(
      "lf.a2a.v1.A2AService",
      "GetExtendedAgentCard",
      _toArrayBuffer(toBinary(GetExtendedAgentCardRequestSchema, request)),
      timeout,
      metadata,
    );
    return fromBinary(AgentCardSchema, new Uint8Array(responseBytes));
  }

  async DeleteTaskPushNotificationConfig(request: DeleteTaskPushNotificationConfigRequest, timeout?: number, metadata?: Map<string, string>): Promise<Empty> {
    const responseBytes = await this._channel.callUnaryAsync(
      "lf.a2a.v1.A2AService",
      "DeleteTaskPushNotificationConfig",
      _toArrayBuffer(toBinary(DeleteTaskPushNotificationConfigRequestSchema, request)),
      timeout,
      metadata,
    );
    return fromBinary(EmptySchema, new Uint8Array(responseBytes));
  }

}

export class A2AServiceGroupClient {
  constructor(private readonly _channel: ChannelLike) {}

  async *SendMessage(request: SendMessageRequest, timeout?: number, metadata?: Map<string, string>): AsyncGenerator<{ context: RpcMessageContext; response: SendMessageResponse }> {
    const reader = await this._channel.callMulticastUnaryAsync(
      "lf.a2a.v1.A2AService",
      "SendMessage",
      _toArrayBuffer(toBinary(SendMessageRequestSchema, request)),
      timeout,
      metadata,
    );
    while (true) {
      const msg = await reader.nextAsync();
      if (msg.tag === MulticastStreamMessage_Tags.End) break;
      if (msg.tag === MulticastStreamMessage_Tags.Error) throw msg.inner.error;
      yield { context: msg.inner.item.context, response: fromBinary(SendMessageResponseSchema, new Uint8Array(msg.inner.item.message)) };
    }
  }

  async *SendStreamingMessage(request: SendMessageRequest, timeout?: number, metadata?: Map<string, string>): AsyncGenerator<{ context: RpcMessageContext; response: StreamResponse }> {
    const reader = await this._channel.callMulticastUnaryStreamAsync(
      "lf.a2a.v1.A2AService",
      "SendStreamingMessage",
      _toArrayBuffer(toBinary(SendMessageRequestSchema, request)),
      timeout,
      metadata,
    );
    while (true) {
      const msg = await reader.nextAsync();
      if (msg.tag === MulticastStreamMessage_Tags.End) break;
      if (msg.tag === MulticastStreamMessage_Tags.Error) throw msg.inner.error;
      yield { context: msg.inner.item.context, response: fromBinary(StreamResponseSchema, new Uint8Array(msg.inner.item.message)) };
    }
  }

  async *GetTask(request: GetTaskRequest, timeout?: number, metadata?: Map<string, string>): AsyncGenerator<{ context: RpcMessageContext; response: Task }> {
    const reader = await this._channel.callMulticastUnaryAsync(
      "lf.a2a.v1.A2AService",
      "GetTask",
      _toArrayBuffer(toBinary(GetTaskRequestSchema, request)),
      timeout,
      metadata,
    );
    while (true) {
      const msg = await reader.nextAsync();
      if (msg.tag === MulticastStreamMessage_Tags.End) break;
      if (msg.tag === MulticastStreamMessage_Tags.Error) throw msg.inner.error;
      yield { context: msg.inner.item.context, response: fromBinary(TaskSchema, new Uint8Array(msg.inner.item.message)) };
    }
  }

  async *ListTasks(request: ListTasksRequest, timeout?: number, metadata?: Map<string, string>): AsyncGenerator<{ context: RpcMessageContext; response: ListTasksResponse }> {
    const reader = await this._channel.callMulticastUnaryAsync(
      "lf.a2a.v1.A2AService",
      "ListTasks",
      _toArrayBuffer(toBinary(ListTasksRequestSchema, request)),
      timeout,
      metadata,
    );
    while (true) {
      const msg = await reader.nextAsync();
      if (msg.tag === MulticastStreamMessage_Tags.End) break;
      if (msg.tag === MulticastStreamMessage_Tags.Error) throw msg.inner.error;
      yield { context: msg.inner.item.context, response: fromBinary(ListTasksResponseSchema, new Uint8Array(msg.inner.item.message)) };
    }
  }

  async *CancelTask(request: CancelTaskRequest, timeout?: number, metadata?: Map<string, string>): AsyncGenerator<{ context: RpcMessageContext; response: Task }> {
    const reader = await this._channel.callMulticastUnaryAsync(
      "lf.a2a.v1.A2AService",
      "CancelTask",
      _toArrayBuffer(toBinary(CancelTaskRequestSchema, request)),
      timeout,
      metadata,
    );
    while (true) {
      const msg = await reader.nextAsync();
      if (msg.tag === MulticastStreamMessage_Tags.End) break;
      if (msg.tag === MulticastStreamMessage_Tags.Error) throw msg.inner.error;
      yield { context: msg.inner.item.context, response: fromBinary(TaskSchema, new Uint8Array(msg.inner.item.message)) };
    }
  }

  async *SubscribeToTask(request: SubscribeToTaskRequest, timeout?: number, metadata?: Map<string, string>): AsyncGenerator<{ context: RpcMessageContext; response: StreamResponse }> {
    const reader = await this._channel.callMulticastUnaryStreamAsync(
      "lf.a2a.v1.A2AService",
      "SubscribeToTask",
      _toArrayBuffer(toBinary(SubscribeToTaskRequestSchema, request)),
      timeout,
      metadata,
    );
    while (true) {
      const msg = await reader.nextAsync();
      if (msg.tag === MulticastStreamMessage_Tags.End) break;
      if (msg.tag === MulticastStreamMessage_Tags.Error) throw msg.inner.error;
      yield { context: msg.inner.item.context, response: fromBinary(StreamResponseSchema, new Uint8Array(msg.inner.item.message)) };
    }
  }

  async *CreateTaskPushNotificationConfig(request: TaskPushNotificationConfig, timeout?: number, metadata?: Map<string, string>): AsyncGenerator<{ context: RpcMessageContext; response: TaskPushNotificationConfig }> {
    const reader = await this._channel.callMulticastUnaryAsync(
      "lf.a2a.v1.A2AService",
      "CreateTaskPushNotificationConfig",
      _toArrayBuffer(toBinary(TaskPushNotificationConfigSchema, request)),
      timeout,
      metadata,
    );
    while (true) {
      const msg = await reader.nextAsync();
      if (msg.tag === MulticastStreamMessage_Tags.End) break;
      if (msg.tag === MulticastStreamMessage_Tags.Error) throw msg.inner.error;
      yield { context: msg.inner.item.context, response: fromBinary(TaskPushNotificationConfigSchema, new Uint8Array(msg.inner.item.message)) };
    }
  }

  async *GetTaskPushNotificationConfig(request: GetTaskPushNotificationConfigRequest, timeout?: number, metadata?: Map<string, string>): AsyncGenerator<{ context: RpcMessageContext; response: TaskPushNotificationConfig }> {
    const reader = await this._channel.callMulticastUnaryAsync(
      "lf.a2a.v1.A2AService",
      "GetTaskPushNotificationConfig",
      _toArrayBuffer(toBinary(GetTaskPushNotificationConfigRequestSchema, request)),
      timeout,
      metadata,
    );
    while (true) {
      const msg = await reader.nextAsync();
      if (msg.tag === MulticastStreamMessage_Tags.End) break;
      if (msg.tag === MulticastStreamMessage_Tags.Error) throw msg.inner.error;
      yield { context: msg.inner.item.context, response: fromBinary(TaskPushNotificationConfigSchema, new Uint8Array(msg.inner.item.message)) };
    }
  }

  async *ListTaskPushNotificationConfigs(request: ListTaskPushNotificationConfigsRequest, timeout?: number, metadata?: Map<string, string>): AsyncGenerator<{ context: RpcMessageContext; response: ListTaskPushNotificationConfigsResponse }> {
    const reader = await this._channel.callMulticastUnaryAsync(
      "lf.a2a.v1.A2AService",
      "ListTaskPushNotificationConfigs",
      _toArrayBuffer(toBinary(ListTaskPushNotificationConfigsRequestSchema, request)),
      timeout,
      metadata,
    );
    while (true) {
      const msg = await reader.nextAsync();
      if (msg.tag === MulticastStreamMessage_Tags.End) break;
      if (msg.tag === MulticastStreamMessage_Tags.Error) throw msg.inner.error;
      yield { context: msg.inner.item.context, response: fromBinary(ListTaskPushNotificationConfigsResponseSchema, new Uint8Array(msg.inner.item.message)) };
    }
  }

  async *GetExtendedAgentCard(request: GetExtendedAgentCardRequest, timeout?: number, metadata?: Map<string, string>): AsyncGenerator<{ context: RpcMessageContext; response: AgentCard }> {
    const reader = await this._channel.callMulticastUnaryAsync(
      "lf.a2a.v1.A2AService",
      "GetExtendedAgentCard",
      _toArrayBuffer(toBinary(GetExtendedAgentCardRequestSchema, request)),
      timeout,
      metadata,
    );
    while (true) {
      const msg = await reader.nextAsync();
      if (msg.tag === MulticastStreamMessage_Tags.End) break;
      if (msg.tag === MulticastStreamMessage_Tags.Error) throw msg.inner.error;
      yield { context: msg.inner.item.context, response: fromBinary(AgentCardSchema, new Uint8Array(msg.inner.item.message)) };
    }
  }

  async *DeleteTaskPushNotificationConfig(request: DeleteTaskPushNotificationConfigRequest, timeout?: number, metadata?: Map<string, string>): AsyncGenerator<{ context: RpcMessageContext; response: Empty }> {
    const reader = await this._channel.callMulticastUnaryAsync(
      "lf.a2a.v1.A2AService",
      "DeleteTaskPushNotificationConfig",
      _toArrayBuffer(toBinary(DeleteTaskPushNotificationConfigRequestSchema, request)),
      timeout,
      metadata,
    );
    while (true) {
      const msg = await reader.nextAsync();
      if (msg.tag === MulticastStreamMessage_Tags.End) break;
      if (msg.tag === MulticastStreamMessage_Tags.Error) throw msg.inner.error;
      yield { context: msg.inner.item.context, response: fromBinary(EmptySchema, new Uint8Array(msg.inner.item.message)) };
    }
  }

}

export interface A2AServiceServicer {
  SendMessage(request: SendMessageRequest, context: ContextLike): Promise<SendMessageResponse>;
  SendStreamingMessage(request: SendMessageRequest, context: ContextLike): AsyncIterable<StreamResponse>;
  GetTask(request: GetTaskRequest, context: ContextLike): Promise<Task>;
  ListTasks(request: ListTasksRequest, context: ContextLike): Promise<ListTasksResponse>;
  CancelTask(request: CancelTaskRequest, context: ContextLike): Promise<Task>;
  SubscribeToTask(request: SubscribeToTaskRequest, context: ContextLike): AsyncIterable<StreamResponse>;
  CreateTaskPushNotificationConfig(request: TaskPushNotificationConfig, context: ContextLike): Promise<TaskPushNotificationConfig>;
  GetTaskPushNotificationConfig(request: GetTaskPushNotificationConfigRequest, context: ContextLike): Promise<TaskPushNotificationConfig>;
  ListTaskPushNotificationConfigs(request: ListTaskPushNotificationConfigsRequest, context: ContextLike): Promise<ListTaskPushNotificationConfigsResponse>;
  GetExtendedAgentCard(request: GetExtendedAgentCardRequest, context: ContextLike): Promise<AgentCard>;
  DeleteTaskPushNotificationConfig(request: DeleteTaskPushNotificationConfigRequest, context: ContextLike): Promise<Empty>;
}

class _A2AService_SendMessage_Handler implements UnaryUnaryHandler {
  constructor(private readonly servicer: A2AServiceServicer) {}

  async handle(request: ArrayBuffer, context: ContextLike): Promise<ArrayBuffer> {
    try {
      const req = fromBinary(SendMessageRequestSchema, new Uint8Array(request));
      const response = await this.servicer.SendMessage(req, context);
      return _toArrayBuffer(toBinary(SendMessageResponseSchema, response));
    } catch (e) {
      throw _toRpcError(e);
    }
  }
}

class _A2AService_SendStreamingMessage_Handler implements UnaryStreamHandler {
  constructor(private readonly servicer: A2AServiceServicer) {}

  async handle(request: ArrayBuffer, context: ContextLike, sink: ResponseSinkLike): Promise<void> {
    try {
      const req = fromBinary(SendMessageRequestSchema, new Uint8Array(request));
      for await (const response of this.servicer.SendStreamingMessage(req, context)) {
        await sink.sendAsync(_toArrayBuffer(toBinary(StreamResponseSchema, response)));
      }
      await sink.closeAsync();
    } catch (e) {
      await sink.sendErrorAsync(_toRpcError(e));
    }
  }
}

class _A2AService_GetTask_Handler implements UnaryUnaryHandler {
  constructor(private readonly servicer: A2AServiceServicer) {}

  async handle(request: ArrayBuffer, context: ContextLike): Promise<ArrayBuffer> {
    try {
      const req = fromBinary(GetTaskRequestSchema, new Uint8Array(request));
      const response = await this.servicer.GetTask(req, context);
      return _toArrayBuffer(toBinary(TaskSchema, response));
    } catch (e) {
      throw _toRpcError(e);
    }
  }
}

class _A2AService_ListTasks_Handler implements UnaryUnaryHandler {
  constructor(private readonly servicer: A2AServiceServicer) {}

  async handle(request: ArrayBuffer, context: ContextLike): Promise<ArrayBuffer> {
    try {
      const req = fromBinary(ListTasksRequestSchema, new Uint8Array(request));
      const response = await this.servicer.ListTasks(req, context);
      return _toArrayBuffer(toBinary(ListTasksResponseSchema, response));
    } catch (e) {
      throw _toRpcError(e);
    }
  }
}

class _A2AService_CancelTask_Handler implements UnaryUnaryHandler {
  constructor(private readonly servicer: A2AServiceServicer) {}

  async handle(request: ArrayBuffer, context: ContextLike): Promise<ArrayBuffer> {
    try {
      const req = fromBinary(CancelTaskRequestSchema, new Uint8Array(request));
      const response = await this.servicer.CancelTask(req, context);
      return _toArrayBuffer(toBinary(TaskSchema, response));
    } catch (e) {
      throw _toRpcError(e);
    }
  }
}

class _A2AService_SubscribeToTask_Handler implements UnaryStreamHandler {
  constructor(private readonly servicer: A2AServiceServicer) {}

  async handle(request: ArrayBuffer, context: ContextLike, sink: ResponseSinkLike): Promise<void> {
    try {
      const req = fromBinary(SubscribeToTaskRequestSchema, new Uint8Array(request));
      for await (const response of this.servicer.SubscribeToTask(req, context)) {
        await sink.sendAsync(_toArrayBuffer(toBinary(StreamResponseSchema, response)));
      }
      await sink.closeAsync();
    } catch (e) {
      await sink.sendErrorAsync(_toRpcError(e));
    }
  }
}

class _A2AService_CreateTaskPushNotificationConfig_Handler implements UnaryUnaryHandler {
  constructor(private readonly servicer: A2AServiceServicer) {}

  async handle(request: ArrayBuffer, context: ContextLike): Promise<ArrayBuffer> {
    try {
      const req = fromBinary(TaskPushNotificationConfigSchema, new Uint8Array(request));
      const response = await this.servicer.CreateTaskPushNotificationConfig(req, context);
      return _toArrayBuffer(toBinary(TaskPushNotificationConfigSchema, response));
    } catch (e) {
      throw _toRpcError(e);
    }
  }
}

class _A2AService_GetTaskPushNotificationConfig_Handler implements UnaryUnaryHandler {
  constructor(private readonly servicer: A2AServiceServicer) {}

  async handle(request: ArrayBuffer, context: ContextLike): Promise<ArrayBuffer> {
    try {
      const req = fromBinary(GetTaskPushNotificationConfigRequestSchema, new Uint8Array(request));
      const response = await this.servicer.GetTaskPushNotificationConfig(req, context);
      return _toArrayBuffer(toBinary(TaskPushNotificationConfigSchema, response));
    } catch (e) {
      throw _toRpcError(e);
    }
  }
}

class _A2AService_ListTaskPushNotificationConfigs_Handler implements UnaryUnaryHandler {
  constructor(private readonly servicer: A2AServiceServicer) {}

  async handle(request: ArrayBuffer, context: ContextLike): Promise<ArrayBuffer> {
    try {
      const req = fromBinary(ListTaskPushNotificationConfigsRequestSchema, new Uint8Array(request));
      const response = await this.servicer.ListTaskPushNotificationConfigs(req, context);
      return _toArrayBuffer(toBinary(ListTaskPushNotificationConfigsResponseSchema, response));
    } catch (e) {
      throw _toRpcError(e);
    }
  }
}

class _A2AService_GetExtendedAgentCard_Handler implements UnaryUnaryHandler {
  constructor(private readonly servicer: A2AServiceServicer) {}

  async handle(request: ArrayBuffer, context: ContextLike): Promise<ArrayBuffer> {
    try {
      const req = fromBinary(GetExtendedAgentCardRequestSchema, new Uint8Array(request));
      const response = await this.servicer.GetExtendedAgentCard(req, context);
      return _toArrayBuffer(toBinary(AgentCardSchema, response));
    } catch (e) {
      throw _toRpcError(e);
    }
  }
}

class _A2AService_DeleteTaskPushNotificationConfig_Handler implements UnaryUnaryHandler {
  constructor(private readonly servicer: A2AServiceServicer) {}

  async handle(request: ArrayBuffer, context: ContextLike): Promise<ArrayBuffer> {
    try {
      const req = fromBinary(DeleteTaskPushNotificationConfigRequestSchema, new Uint8Array(request));
      const response = await this.servicer.DeleteTaskPushNotificationConfig(req, context);
      return _toArrayBuffer(toBinary(EmptySchema, response));
    } catch (e) {
      throw _toRpcError(e);
    }
  }
}
export function registerA2AServiceServicer(server: ServerLike, servicer: A2AServiceServicer): void {
  server.registerUnaryUnary("lf.a2a.v1.A2AService", "SendMessage", new _A2AService_SendMessage_Handler(servicer));
  server.registerUnaryStream("lf.a2a.v1.A2AService", "SendStreamingMessage", new _A2AService_SendStreamingMessage_Handler(servicer));
  server.registerUnaryUnary("lf.a2a.v1.A2AService", "GetTask", new _A2AService_GetTask_Handler(servicer));
  server.registerUnaryUnary("lf.a2a.v1.A2AService", "ListTasks", new _A2AService_ListTasks_Handler(servicer));
  server.registerUnaryUnary("lf.a2a.v1.A2AService", "CancelTask", new _A2AService_CancelTask_Handler(servicer));
  server.registerUnaryStream("lf.a2a.v1.A2AService", "SubscribeToTask", new _A2AService_SubscribeToTask_Handler(servicer));
  server.registerUnaryUnary("lf.a2a.v1.A2AService", "CreateTaskPushNotificationConfig", new _A2AService_CreateTaskPushNotificationConfig_Handler(servicer));
  server.registerUnaryUnary("lf.a2a.v1.A2AService", "GetTaskPushNotificationConfig", new _A2AService_GetTaskPushNotificationConfig_Handler(servicer));
  server.registerUnaryUnary("lf.a2a.v1.A2AService", "ListTaskPushNotificationConfigs", new _A2AService_ListTaskPushNotificationConfigs_Handler(servicer));
  server.registerUnaryUnary("lf.a2a.v1.A2AService", "GetExtendedAgentCard", new _A2AService_GetExtendedAgentCard_Handler(servicer));
  server.registerUnaryUnary("lf.a2a.v1.A2AService", "DeleteTaskPushNotificationConfig", new _A2AService_DeleteTaskPushNotificationConfig_Handler(servicer));
}
