// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// Public barrel for the generated A2A v1.0.0 bindings:
//   * protobuf-es v2 message types + schemas (a2a_pb)
//   * slimrpc client/group/servicer/register stubs (a2a_slimrpc)
//
// These files are generated by `npm run generate`; do not edit them by hand.
export * from './a2a_pb.js';
export * from './a2a_slimrpc.js';
